[build]
builder = "nixpacks"
buildCommand = "cd social-media-module/backend && pip install --no-cache-dir -r requirements-prod.txt"

[deploy]
startCommand = "cd social-media-module/backend && uvicorn api.main:app --host 0.0.0.0 --port $PORT --workers 2 --worker-class uvicorn.workers.UvicornWorker --access-log --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
WEB_CONCURRENCY = "2"

[observability]
enabled = true
